name: Deploy Static HTML

on:
  push:
    branches:
      - main # Chạy khi có thay đổi trong nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Thư mục chứa file HTML tĩnh
